version: 2

models:
  - name: dim_patients
    description: "Dimension table holding cleaned patient demographic information."
    columns:
      - name: patient_id
        description: "Unique identifier for the patient."
        tests:
          - unique
          - not_null
      - name: gender
        description: "Patient's gender."
        tests:
          - accepted_values:
              values: ['Male', 'Female'] 
      - name: insurance_status
        tests:
          - not_null

  - name: int_admissions_details
    columns:
      - name: patient_id
        tests:
          - relationships: # Foreign key test
              to: ref('dim_patients')
              field: patient_id